### ISSUE TITLE
code for access point

### ISSUE THREAD

**Issue by luftpumpe83** [AK-Homberger/Satellite-Dish-Positioner#2]
Hi,
could you please also upload a changed version of your sketch to work as an access point?
I've tried on my own with code samples I've found on several websites but can't get it working. I'm no programmer ;)
This would be very nice of you.
Thanks in advance!

**Comment by AK-Homberger** [comment]
Hi,

PLease have a look to the Anchor Chain Remote Code: https://github.com/AK-Homberger/ESP8266_AnchorChainControl_WLAN

You can use the same WiFi Code to implement the AP function for the Satellite Sketch.

Regards,
Andreas

**Comment by luftpumpe83** [comment]
Hi,
thank you so much. It's working!
Regards,
Olli
