### ISSUE TITLE
Use stepper motors instead of Diseqc motors

### ISSUE THREAD

**Issue by WK-Eider** [AK-Homberger/Satellite-Dish-Positioner#3]
I have a fully automatic satellite dish, unfortunately with water damage and the electronics are defective.
Now I want to use your solution. Unfortunately I have a stepper motor for each level.
For the elevation I will be able to convert the sketch for a stepper motor. But with the azimuth drive, a lot is done in the Diseqc motor module. I'm not quite sure about that yet.
Is there any further information?
Or do you have any tips for me?
Thanks !!

**Comment by AK-Homberger** [comment]
It should be possible to change the code for stepper motors. Just replace the Disqc part with the same general code as for the elevation. Unfortunately, I don't have any example code for stepper motors.
