### ISSUE TITLE
Motoren bewegen sich nicht

### ISSUE THREAD

**Issue by ratzl** [AK-Homberger/Satellite-Dish-Positioner#5]
Hallo,

ich habe die Platine nachgebaut und bin gerade bei der Inbetriebnahme.

Die beiden Sensorboards sind noch nicht angeschlossen.

Wenn ich im Webinterface auf AutoOFF schalte und die Schieber bewege reagieren die Motoren nicht.

Ich habe auch schon das Signal vom Rotor angeschaut, die Frequenz ist 27khz anstatt 22khz.

Was mache ich falsch?

Viele Grüße
Matthias

**Comment by AK-Homberger** [comment]
Hallo Matthias,

ohne die Sensor-Boards habe ich das noch nie ausprobiert. Nach kurzer Sichtung des Codes sollte es aber gehen (Aber ohne absolute Gewähr).

Der Rotor sollte sich bei "Auto:Off" mit dem Rotor-Schiber bewegen lassen.

Der Linearmotor aber nicht. Dadurch das er kein Lagesignal hat, hat er keine Referenz und "Motor Error" ist zu hoch.

Wie hast du denn die Frequenz gemessen? Das Signal wird durch Zählen der der Microsekunden erzeugt:

void write0() {                      // write a '0' bit toneburst
  for (int i = 1; i <= 22; i++) {    // 1 ms of 22 kHz (22 cycles)
    digitalWrite(datapin, HIGH);
    delayMicroseconds(16);
    digitalWrite(datapin, LOW);
    delayMicroseconds(17);
  }
  delayMicroseconds(500);             // 0.5 ms of silence
}

Wenn die Frequenz nicht stimmt, kann das eigentlich nur dadurch kommen, dass das Timing des ESP8266 gestört ist. Eventuell durch das Fehlen der Sensoren.

Du kannst den Rotor-Code ja einmal in einem kleinen eigenen Sketch laufen lassen.

Viele Grüße
Andreas

**Comment by ratzl** [comment]
Hallo Andreas,

Ich habe das Signal mit einem Oszi gemessen.

Der Code den du gepostet hast, erzeugt doch aber eher einen Toneburst mit einer Frequenz von ca. 1(16us+17us) = 30303 Hz und einer Dauer von 22x(16us+17us)= 7.26ms ? 

Sobald die Sensoren da sind werde ich noch mal berichten

Grüße
Matthias

**Comment by AK-Homberger** [comment]
Deine Berechnung ist so nicht OK. Schau dir am Besten mal die verlinkte Diseqc-Spezifikation an (Datei: simple_tone_burst_detec.pdf im ZIP-File). Dann wird es bestimmt klarer.

**Comment by ratzl** [comment]
Hier das Signal 

![SCR01](https://user-images.githubusercontent.com/16897388/118778243-2d4dc080-b88a-11eb-9411-8e6fb3688932.PNG)

**Comment by ratzl** [comment]
Erstes Bild war im Leerlauf
Folgende Bilder mit angeschlossenem Motor

![SCR02](https://user-images.githubusercontent.com/16897388/118781539-74898080-b88d-11eb-93b1-318131ec686d.PNG)
![SCR03](https://user-images.githubusercontent.com/16897388/118781543-76534400-b88d-11eb-85a2-0bcb104f9b67.PNG)

**Comment by AK-Homberger** [comment]
Ich hab mir den Code nochmal angesehen. Die Quelle (Solartracker) lief auf einem langsameren Arduino. Für den schnelleren ESP8266 sind die Zeiten (16/17 Mikrosekunden) zu kurz. Erhöhe die mal schrittweise bis es passt (ca. 20 bis 25).

Und danke für den Hinweis. Es hat zwar bei mir trotzdem funktioniert. Mit 27.55 kHz Ist das aber doch etwas weit aus der Spezifikation. 

Kanst du mir die finalen Werte senden. Mein Hameg kann leider keine automatische Frequenzanzeige.

Ich werde das Programm und die Dokumentation dann entsprechend anpassen.

**Comment by ratzl** [comment]
Habe jetzt mal den Code so angepasst wie ich das verstehe, jetzt kann ich den Motor bewegen.
Ich habe auch nicht den exakt gleichen Motor verwendet wie in deinem Link(der ist nämlich nicht mehr verfügbar) Ich vermute dein Motor kommt auch mit 27khz zurecht.

Hier meine Änderung:

void write0() {                      // write a '0' bit toneburst
  for (int i = 1; i <= 22; i++) {    // 1 ms of 22 kHz (22 cycles)
    digitalWrite(datapin, HIGH);
    delayMicroseconds(22);
    digitalWrite(datapin, LOW);
    delayMicroseconds(23);
  }
  delayMicroseconds(500);             // 0.5 ms of silence
}

void write1() {                      // write a '1' bit toneburst
  for (int i = 1; i <= 11; i++) {    // 0.5 ms of 22 kHz (11 cycles)
    digitalWrite(datapin, HIGH);
    delayMicroseconds(22);
    digitalWrite(datapin, LOW);
    delayMicroseconds(23);
  }
  delayMicroseconds(1000);            // 1 ms of silence
}
1/45us = 22222khz,  und davon 22 Zyklen ergeben 1ms, bzw. 11 Zyklen = 0,5ms

**Comment by ratzl** [comment]
die 22 bzw. 23 ergeben dann gemessen am Oszi 20,7 khz, das liegt innerhalb der Spec

**Comment by AK-Homberger** [comment]
Ich setze dann beide auf 22. Das sollte noch etwas näher dran sein. Funktioniert jetzt der Motor?

**Comment by ratzl** [comment]
Ja der Rotor dreht, jetzt warte ich noch auf die Sensoren.

Vielen Dank ;)
