### ISSUE TITLE
GY-271 

### ISSUE THREAD

**Issue by ratzl** [AK-Homberger/Satellite-Dish-Positioner#6]
Hallo Andreas,

ich habe bereits bei zwei verschiedenen Lieferanten den GY-271 bestellt, leider ist darauf immer der  HMC5883L Chip verbaut, auch bei AZ-Delivery. Nach Rückfrage bei AZ-Delivery  wurde mir mitgeteilt , dass sie nur noch den auf Lager haben. Könntest du evtl. den Code so anpassen, dass auch der  HMC5883L Chip funktioniert?

Viele Grüße
Matthias

**Comment by AK-Homberger** [comment]
Hallo Matthias,
da ich kein Device mit dem Chip habe, kann ich es leider nicht testen. Aber sehe dir doch einfach die Beispiele in der Bibliothek für den HMC5883L an. Du musst nur die Include-Datei, die Initialisierung in setup() und die Funktion für die Richtung austauschen. Ich bin sicher, das schaffst du auch selbst.
Viele Grüße 
Andreas

**Comment by joalbauer** [comment]
Hallo Matthias, 
ich habe einen GY-271 bei makershop bestellt und einen GY-271 mit **Q**MC5883 Chip bekommen für 4,75€ Versand war ab 10€ kostenlos und auch recht zügig. [https://www.makershop.de/sensoren/gy-271-hmc5883l/](url)

Ich habe gelesen, dass der **H**MC5883L Chip von Honeywell gar nicht mehr produziert wird und deshalb viele auf den "Q-Chip" ausweichen, der hat aber eine andere I2C ID und wird anscheinend auch anders angesprochen, so dass die beiden Chips nicht direkt kompatibel sind. 
Gruß Jochen

**Comment by ratzl** [comment]
Hallo Jochen,
danke für den Tipp, habe den GY-271 schon bekommen.
Preis und Versand sind Top.
Grüße
Matthias
