### ISSUE TITLE
Feature request: Add support for GPS module for automatic calculation of sat positioning data from latitude & longitude

### ISSUE THREAD

**Issue by joalbauer** [AK-Homberger/Satellite-Dish-Positioner#7]
Awesome project! I have started to build a dish myself. While looking through my electronics parts box I stumbled upon an old GPS module. To take automation further ahead I would like to suggest adding support for GPS modules. Modules supporting 3.3V TTL level and NMEA protocol (9600bps serial connection if I remember correctly) are readily available at ebay or amazon for around 20€ . With the latitude and longitude determined via GPS it should be possible to calculate the required positioning data (i.e. azimuth and elevation) for the satellite of your choice without having to enter these data manually any more. I could try to find a way to implement such a function myself. But first I need to finish my built with the current version.

**Comment by AK-Homberger** [comment]
Feel free to fork the project and implement the calculation by yourself. I don't see the need for such a feature currently, bacause I'm not travelling long distances that would require this function.
