### ISSUE TITLE
AzimutOffset

### ISSUE THREAD

**Issue by dewilldi** [AK-Homberger/Satellite-Dish-Positioner#8]
Im Artikel der Make von 2/2021 steht auf Seite 58 "Die Abweichung für den Kompasswird dann bei AzimutOffser eingetragen". Das hört sich ganz einfach an, ich habe es aber nicht hinbekommen. Habe den AzimutOffset auf 0 gesetzt, habe die Automatik eingeschaltet, gewartet bis sich die Schüssel ausgerichtet hat, dann die Automatik mit R-Off ausgeschaltet und mit SETP+ bzw. -STEP die Schüssel korrekt ausgerichtet. Jetzt wird mir bei Rotor ein Wert angezeigt. Wird dieser einfach als AzimutOffset eingetragen und wenn ja mit welchem Vorzeichen?

**Comment by AK-Homberger** [comment]
Hallo,
bei der aktuellen Programmversion muss nichts mehr im Programm geändert werden. Einfach den Offset im Fenster "Satfinder Settings" bei "Azimut Offset" eintragen.

Allerdings funktioniert das nicht mit Step+/Step- sondern mit "Delta Azimut" Up/Down. 
Den Wert für die korrekte Ausrichtung dann bei "Azimut Offest" eintagen. Dann sollte die korrekte Ausrichtung bei "Delta Azimut"=0 vorhanden sein, wobei eventuell kleine Korrekturen mit Step+/Step- nötig sein können (bei R-Off). Man kann das beliebig oft ändern, bis es passt.

Viele Grüße
Andreas
